apiVersion: v1
kind: Service
metadata:
  name: micro-service
spec:
  selector:
    app: micro-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-app
spec:
  selector:
    matchLabels:
      app: micro-app
  replicas: 5
  template:
    metadata:
      labels:
        app: micro-app
    spec:
      containers:
      - name: micro-app
        image: microapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000